In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sweetviz
from sklearn.preprocessing import OrdinalEncoder

In [2]:
train_df = pd.read_csv("rossmann-store-sales/train.csv", low_memory=False)
test_df = pd.read_csv("rossmann-store-sales/test.csv", low_memory=False)
store_df = pd.read_csv("rossmann-store-sales/store.csv", low_memory=False)

In [3]:
train_df.head()

Store  DayOfWeek        Date  Sales  Customers  Open  Promo StateHoliday  \
0      1          5  2015-07-31   5263        555     1      1            0   
1      2          5  2015-07-31   6064        625     1      1            0   
2      3          5  2015-07-31   8314        821     1      1            0   
3      4          5  2015-07-31  13995       1498     1      1            0   
4      5          5  2015-07-31   4822        559     1      1            0   

   SchoolHoliday  
0              1  
1              1  
2              1  
3              1  
4              1

In [4]:
test_df.head()

Id  Store  DayOfWeek        Date  Open  Promo StateHoliday  SchoolHoliday
0   1      1          4  2015-09-17   1.0      1            0              0
1   2      3          4  2015-09-17   1.0      1            0              0
2   3      7          4  2015-09-17   1.0      1            0              0
3   4      8          4  2015-09-17   1.0      1            0              0
4   5      9          4  2015-09-17   1.0      1            0              0

In [5]:
store_df.head()

Store StoreType Assortment  CompetitionDistance  CompetitionOpenSinceMonth  \
0      1         c          a               1270.0                        9.0   
1      2         a          a                570.0                       11.0   
2      3         a          a              14130.0                       12.0   
3      4         c          c                620.0                        9.0   
4      5         a          a              29910.0                        4.0   

   CompetitionOpenSinceYear  Promo2  Promo2SinceWeek  Promo2SinceYear  \
0                    2008.0       0              NaN              NaN   
1                    2007.0       1             13.0           2010.0   
2                    2006.0       1             14.0           2011.0   
3                    2009.0       0              NaN              NaN   
4                    2015.0       0              NaN              NaN   

     PromoInterval  
0              NaN  
1  Jan,Apr,Jul,Oct  
2  Jan,Apr,Jul,Oct  
3              NaN  
4              NaN

## Dataset analysis
### Level of data:
* train_df: Store-Date
* test_df: Store-Date
* store_df: Store

In [6]:
print("Number of records in train_df: ", len(train_df))
print("Number of records in test_df: ", len(test_df))
print("Number of records in store_df: ", len(store_df))

print("Number of unique stores: ", train_df['Store'].nunique())
print("Number of unique ids (test set): ", test_df['Id'].nunique())

Number of records in train_df:  1017209
Number of records in test_df:  41088
Number of records in store_df:  1115
Number of unique stores:  1115
Number of unique ids (test set):  41088


## Merge Dataset

In [7]:
train_data = pd.merge(train_df, store_df, how='inner', on='Store')
test_data = pd.merge(test_df, store_df, how='inner', on='Store')
print(len(train_data))
print(len(test_data))

1017209
41088


In [8]:
print(train_data.shape)
print(test_data.shape)

(1017209, 18)
(41088, 17)


In [9]:
train_data

Store  DayOfWeek        Date  Sales  Customers  Open  Promo  \
0            1          5  2015-07-31   5263        555     1      1   
1            1          4  2015-07-30   5020        546     1      1   
2            1          3  2015-07-29   4782        523     1      1   
3            1          2  2015-07-28   5011        560     1      1   
4            1          1  2015-07-27   6102        612     1      1   
...        ...        ...         ...    ...        ...   ...    ...   
1017204   1115          6  2013-01-05   4771        339     1      0   
1017205   1115          5  2013-01-04   4540        326     1      0   
1017206   1115          4  2013-01-03   4297        300     1      0   
1017207   1115          3  2013-01-02   3697        305     1      0   
1017208   1115          2  2013-01-01      0          0     0      0   

        StateHoliday  SchoolHoliday StoreType Assortment  CompetitionDistance  \
0                  0              1         c          a               1270.0   
1                  0              1         c          a               1270.0   
2                  0              1         c          a               1270.0   
3                  0              1         c          a               1270.0   
4                  0              1         c          a               1270.0   
...              ...            ...       ...        ...                  ...   
1017204            0              1         d          c               5350.0   
1017205            0              1         d          c               5350.0   
1017206            0              1         d          c               5350.0   
1017207            0              1         d          c               5350.0   
1017208            a              1         d          c               5350.0   

         CompetitionOpenSinceMonth  CompetitionOpenSinceYear  Promo2  \
0                              9.0                    2008.0       0   
1                              9.0                    2008.0       0   
2                              9.0                    2008.0       0   
3                              9.0                    2008.0       0   
4                              9.0                    2008.0       0   
...                            ...                       ...     ...   
1017204                        NaN                       NaN       1   
1017205                        NaN                       NaN       1   
1017206                        NaN                       NaN       1   
1017207                        NaN                       NaN       1   
1017208                        NaN                       NaN       1   

         Promo2SinceWeek  Promo2SinceYear     PromoInterval  
0                    NaN              NaN               NaN  
1                    NaN              NaN               NaN  
2                    NaN              NaN               NaN  
3                    NaN              NaN               NaN  
4                    NaN              NaN               NaN  
...                  ...              ...               ...  
1017204             22.0           2012.0  Mar,Jun,Sept,Dec  
1017205             22.0           2012.0  Mar,Jun,Sept,Dec  
1017206             22.0           2012.0  Mar,Jun,Sept,Dec  
1017207             22.0           2012.0  Mar,Jun,Sept,Dec  
1017208             22.0           2012.0  Mar,Jun,Sept,Dec  

[1017209 rows x 18 columns]

In [10]:
test_data

Id  Store  DayOfWeek        Date  Open  Promo StateHoliday  \
0          1      1          4  2015-09-17   1.0      1            0   
1        857      1          3  2015-09-16   1.0      1            0   
2       1713      1          2  2015-09-15   1.0      1            0   
3       2569      1          1  2015-09-14   1.0      1            0   
4       3425      1          7  2015-09-13   0.0      0            0   
...      ...    ...        ...         ...   ...    ...          ...   
41083  37664   1115          3  2015-08-05   1.0      1            0   
41084  38520   1115          2  2015-08-04   1.0      1            0   
41085  39376   1115          1  2015-08-03   1.0      1            0   
41086  40232   1115          7  2015-08-02   0.0      0            0   
41087  41088   1115          6  2015-08-01   1.0      0            0   

       SchoolHoliday StoreType Assortment  CompetitionDistance  \
0                  0         c          a               1270.0   
1                  0         c          a               1270.0   
2                  0         c          a               1270.0   
3                  0         c          a               1270.0   
4                  0         c          a               1270.0   
...              ...       ...        ...                  ...   
41083              1         d          c               5350.0   
41084              1         d          c               5350.0   
41085              1         d          c               5350.0   
41086              1         d          c               5350.0   
41087              1         d          c               5350.0   

       CompetitionOpenSinceMonth  CompetitionOpenSinceYear  Promo2  \
0                            9.0                    2008.0       0   
1                            9.0                    2008.0       0   
2                            9.0                    2008.0       0   
3                            9.0                    2008.0       0   
4                            9.0                    2008.0       0   
...                          ...                       ...     ...   
41083                        NaN                       NaN       1   
41084                        NaN                       NaN       1   
41085                        NaN                       NaN       1   
41086                        NaN                       NaN       1   
41087                        NaN                       NaN       1   

       Promo2SinceWeek  Promo2SinceYear     PromoInterval  
0                  NaN              NaN               NaN  
1                  NaN              NaN               NaN  
2                  NaN              NaN               NaN  
3                  NaN              NaN               NaN  
4                  NaN              NaN               NaN  
...                ...              ...               ...  
41083             22.0           2012.0  Mar,Jun,Sept,Dec  
41084             22.0           2012.0  Mar,Jun,Sept,Dec  
41085             22.0           2012.0  Mar,Jun,Sept,Dec  
41086             22.0           2012.0  Mar,Jun,Sept,Dec  
41087             22.0           2012.0  Mar,Jun,Sept,Dec  

[41088 rows x 17 columns]

In [11]:
my_report = sweetviz.analyze([train_data, "train"], target_feat="Sales")

                                             |      | [  0%]   00:00 -> (? left)

In [12]:
my_report.show_html()

Report SWEETVIZ_REPORT.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.


## Testing Entity Embedding model

In [235]:
import Cat2Emb as c2e
from sklearn.model_selection import train_test_split
import imp
imp.reload(c2e)

<module 'Cat2Emb' from '/Users/suvendukumarpati/Documents/Cat2Emb/Cat2Emb.py'>

In [74]:
X_train, y_train =train_data.drop(['Sales'],axis=1), train_data['Sales']
print(X_train.shape)
print(y_train.shape)

(1017209, 17)
(1017209,)


In [191]:
var = ['Store', 'Open', 'StoreType', 'DayOfWeek', 'Assortment', 'SchoolHoliday']

In [199]:
X_train['Store'] = X_train['Store'].astype('object')
X_train['DayOfWeek'] = X_train['DayOfWeek'].astype('object')
X_train[var].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1017209 entries, 0 to 1017208
Data columns (total 6 columns):
 #   Column         Non-Null Count    Dtype 
---  ------         --------------    ----- 
 0   Store          1017209 non-null  object
 1   Open           1017209 non-null  int64 
 2   StoreType      1017209 non-null  object
 3   DayOfWeek      1017209 non-null  object
 4   Assortment     1017209 non-null  object
 5   SchoolHoliday  1017209 non-null  int64 
dtypes: int64(2), object(4)
memory usage: 54.3+ MB


In [200]:
X_train[var].head()

Store  Open StoreType DayOfWeek Assortment  SchoolHoliday
0     1     1         c         5          a              1
1     1     1         c         4          a              1
2     1     1         c         3          a              1
3     1     1         c         2          a              1
4     1     1         c         1          a              1

In [206]:
print(test_data['Open'].isnull().sum())
print(test_data['Open'].value_counts())

11
1.0    35093
0.0     5984
Name: Open, dtype: int64


In [208]:
test_data['Open'] = test_data['Open'].fillna(1).astype(np.int64)
test_data['Store'] = test_data['Store'].astype('object')
test_data['DayOfWeek'] = test_data['DayOfWeek'].astype('object')
test_data[var].info()
test_data[var].head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 41088 entries, 0 to 41087
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Store          41088 non-null  object
 1   Open           41088 non-null  int64 
 2   StoreType      41088 non-null  object
 3   DayOfWeek      41088 non-null  object
 4   Assortment     41088 non-null  object
 5   SchoolHoliday  41088 non-null  int64 
dtypes: int64(2), object(4)
memory usage: 2.2+ MB


Store  Open StoreType DayOfWeek Assortment  SchoolHoliday
0     1     1         c         4          a              0
1     1     1         c         3          a              0
2     1     1         c         2          a              0
3     1     1         c         1          a              0
4     1     0         c         7          a              0

In [236]:
embed_model = c2e.EmbeddingGenerator(epochs=5)
embed_model.fit(X_train[var], y_train)

Epoch 1/5
7947/7947 [==============================] - 6s 703us/step - loss: 1434.1783 - mean_absolute_error: 1434.1783
Epoch 2/5
7947/7947 [==============================] - 6s 699us/step - loss: 1141.4464 - mean_absolute_error: 1141.4464
Epoch 3/5
7947/7947 [==============================] - 6s 696us/step - loss: 1140.2664 - mean_absolute_error: 1140.2664
Epoch 4/5
7947/7947 [==============================] - 6s 698us/step - loss: 1139.7506 - mean_absolute_error: 1139.7506
Epoch 5/5
7947/7947 [==============================] - 6s 702us/step - loss: 1139.2823 - mean_absolute_error: 1139.2823


In [238]:
train_prediction = embed_model.predict(X_train[var])
print(len(train_prediction))

31788/31788 [==============================] - 11s 346us/step
1017209


In [239]:
test_prediction = embed_model.predict(test_data[var])

1284/1284 [==============================] - 0s 355us/step


In [237]:
train_transformed = embed_model.transform(X_train[var])
train_transformed.head()

Store  Open StoreType DayOfWeek Assortment  SchoolHoliday   Store_0  \
0     1     1         c         5          a              1  0.053904   
1     1     1         c         5          a              0  0.053904   
2     1     1         c         5          a              0  0.053904   
3     1     1         c         5          a              0  0.053904   
4     1     1         c         5          a              0  0.053904   

    Store_1  StoreType_0  StoreType_1  DayOfWeek_0  DayOfWeek_1  Assortment_0  \
0 -0.115591      0.87381     0.829139    -0.630595    -0.619439     -0.915378   
1 -0.115591      0.87381     0.829139    -0.630595    -0.619439     -0.915378   
2 -0.115591      0.87381     0.829139    -0.630595    -0.619439     -0.915378   
3 -0.115591      0.87381     0.829139    -0.630595    -0.619439     -0.915378   
4 -0.115591      0.87381     0.829139    -0.630595    -0.619439     -0.915378   

   Assortment_1  
0      0.957468  
1      0.957468  
2      0.957468  
3      0.957468  
4      0.957468

In [240]:
test_transformed = embed_model.transform(test_data[var])
test_transformed.head()

Store  Open StoreType DayOfWeek Assortment  SchoolHoliday   Store_0  \
0     1     1         c         4          a              0  0.053904   
1     1     1         c         4          a              0  0.053904   
2     1     1         c         4          a              1  0.053904   
3     1     1         c         4          a              1  0.053904   
4     1     1         c         4          a              1  0.053904   

    Store_1  StoreType_0  StoreType_1  DayOfWeek_0  DayOfWeek_1  Assortment_0  \
0 -0.115591      0.87381     0.829139    -0.462634     -0.44061     -0.915378   
1 -0.115591      0.87381     0.829139    -0.462634     -0.44061     -0.915378   
2 -0.115591      0.87381     0.829139    -0.462634     -0.44061     -0.915378   
3 -0.115591      0.87381     0.829139    -0.462634     -0.44061     -0.915378   
4 -0.115591      0.87381     0.829139    -0.462634     -0.44061     -0.915378   

   Assortment_1  
0      0.957468  
1      0.957468  
2      0.957468  
3      0.957468  
4      0.957468

In [245]:
def get_embeddings_plot(colname, transformed_data):
    col = [colname, f'{colname}_0', f'{colname}_1']
    x = transformed_data[col].drop_duplicates().reset_index(drop=True)
    return x
    
    # a = pd.DataFrame(embed_model.model.get_layer(colname).get_weights()[0]).reset_index().rename({'index':colname}, axis=1)
    # a.columns = [colname, 'feature_1', 'feature_2']
    # a[colname] = [i+1 for i in range(7)]
    # return a

plotdf = get_embeddings_plot('DayOfWeek', train_transformed)
plotdf

DayOfWeek  DayOfWeek_0  DayOfWeek_1
0         5    -0.630595    -0.619439
1         4    -0.462634    -0.440610
2         3    -0.475001    -0.430863
3         2    -0.633697    -0.568943
4         1    -1.223648    -1.198078
5         7    -0.484520    -0.476493
6         6    -0.010288     0.006231

In [244]:
import seaborn as sns
import matplotlib.pyplot as plt

sns.scatterplot(data=plotdf, x='feature_1', y='feature_2', hue='DayOfWeek', palette='deep', s=50)
plt.legend(title='DayOfWeek')

ValueError: Could not interpret value `feature_1` for parameter `x`

In [180]:
b = pd.concat([X_train, y_train],axis=1)
pd.DataFrame(b.groupby('DayOfWeek')['Sales'].mean()).reset_index().rename({'Sales':'mean_sales'},axis=1)

DayOfWeek   mean_sales
0          1  7809.044510
1          2  7005.244467
2          3  6555.884138
3          4  6247.575913
4          5  6723.274305
5          6  5847.562599
6          7   204.183189

In [120]:
train_pred = embed_model.predict(X_train[var])
test_pred = embed_model.predict(test_data[var])

[array([   0,    0,    0, ..., 1114, 1114, 1114], dtype=int32), array([2, 2, 2, ..., 3, 3, 3], dtype=int32)]
total inputs: 
31788/31788 [==============================] - 11s 333us/step


TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [109]:
X_train_embeddings = embed_model.transform(X_train[var])
X_train_embeddings

      Store  Store_index
0         1            0
1         2            1
2         3            2
3         4            3
4         5            4
...     ...          ...
1110   1111         1110
1111   1112         1111
1112   1113         1112
1113   1114         1113
1114   1115         1114

[1115 rows x 2 columns]
  StoreType  StoreType_index
0         a                0
1         b                1
2         c                2
3         d                3


Store  Open StoreType   Store_0   Store_1   Store_2   Store_3  \
0           1     1         c -0.046380 -0.070164 -0.085546  0.054663   
1           1     1         c  0.000000  0.000000  0.000000  0.000000   
2           1     1         c -0.046380 -0.070164 -0.085546  0.054663   
3           1     1         c  0.000000  0.000000  0.000000  0.000000   
4           1     1         c -0.046380 -0.070164 -0.085546  0.054663   
...       ...   ...       ...       ...       ...       ...       ...   
1569773  1097     1         b -0.211977 -0.241613 -0.279667  0.238646   
1569774  1097     1         b -0.211977 -0.241613 -0.279667  0.238646   
1569775  1097     1         b -0.211977 -0.241613 -0.279667  0.238646   
1569776  1097     1         b -0.211977 -0.241613 -0.279667  0.238646   
1569777  1097     1         b -0.211977 -0.241613 -0.279667  0.238646   

          Store_4   Store_5   Store_6  ...  Store_42  Store_43  Store_44  \
0       -0.082964  0.040431  0.059235  ...  0.079152  0.038204 -0.098588   
1        0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
2       -0.082964  0.040431  0.059235  ...  0.079152  0.038204 -0.098588   
3        0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
4       -0.082964  0.040431  0.059235  ...  0.079152  0.038204 -0.098588   
...           ...       ...       ...  ...       ...       ...       ...   
1569773 -0.238251  0.216923  0.253797  ...  0.245005  0.259364 -0.240164   
1569774 -0.238251  0.216923  0.253797  ...  0.245005  0.259364 -0.240164   
1569775 -0.238251  0.216923  0.253797  ...  0.245005  0.259364 -0.240164   
1569776 -0.238251  0.216923  0.253797  ...  0.245005  0.259364 -0.240164   
1569777 -0.238251  0.216923  0.253797  ...  0.245005  0.259364 -0.240164   

         Store_45  Store_46  Store_47  Store_48  Store_49  StoreType_0  \
0        0.007321  0.102424 -0.078481 -0.059800 -0.035342     0.606390   
1        0.000000  0.000000  0.000000  0.000000  0.000000     0.606390   
2        0.007321  0.102424 -0.078481 -0.059800 -0.035342     0.606390   
3        0.000000  0.000000  0.000000  0.000000  0.000000     0.606390   
4        0.007321  0.102424 -0.078481 -0.059800 -0.035342     0.606390   
...           ...       ...       ...       ...       ...          ...   
1569773  0.220367  0.308087 -0.232557 -0.267985 -0.261742     0.342286   
1569774  0.220367  0.308087 -0.232557 -0.267985 -0.261742     0.342286   
1569775  0.220367  0.308087 -0.232557 -0.267985 -0.261742     0.342286   
1569776  0.220367  0.308087 -0.232557 -0.267985 -0.261742     0.342286   
1569777  0.220367  0.308087 -0.232557 -0.267985 -0.261742     0.342286   

         StoreType_1  
0          -0.532044  
1          -0.532044  
2          -0.532044  
3          -0.532044  
4          -0.532044  
...              ...  
1569773    -0.444455  
1569774    -0.444455  
1569775    -0.444455  
1569776    -0.444455  
1569777    -0.444455  

[1569778 rows x 55 columns]

In [112]:
test_data['Store'] = test_data['Store'].astype('category')
X_test_embeddings = embed_model.transform(test_data[var])
X_test_embeddings

      Store  Store_index
0         1            0
1         2            1
2         3            2
3         4            3
4         5            4
...     ...          ...
1110   1111         1110
1111   1112         1111
1112   1113         1112
1113   1114         1113
1114   1115         1114

[1115 rows x 2 columns]
  StoreType  StoreType_index
0         a                0
1         b                1
2         c                2
3         d                3


Store  Open StoreType   Store_0   Store_1   Store_2   Store_3  \
0          1   1.0         c -0.046380 -0.070164 -0.085546  0.054663   
1          1   1.0         c  0.000000  0.000000  0.000000  0.000000   
2          1   1.0         c -0.046380 -0.070164 -0.085546  0.054663   
3          1   1.0         c  0.000000  0.000000  0.000000  0.000000   
4          1   1.0         c -0.046380 -0.070164 -0.085546  0.054663   
...      ...   ...       ...       ...       ...       ...       ...   
63259   1097   1.0         b -0.211977 -0.241613 -0.279667  0.238646   
63260   1097   1.0         b -0.211977 -0.241613 -0.279667  0.238646   
63261   1097   1.0         b -0.211977 -0.241613 -0.279667  0.238646   
63262   1097   1.0         b -0.211977 -0.241613 -0.279667  0.238646   
63263   1097   1.0         b -0.211977 -0.241613 -0.279667  0.238646   

        Store_4   Store_5   Store_6  ...  Store_42  Store_43  Store_44  \
0     -0.082964  0.040431  0.059235  ...  0.079152  0.038204 -0.098588   
1      0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
2     -0.082964  0.040431  0.059235  ...  0.079152  0.038204 -0.098588   
3      0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
4     -0.082964  0.040431  0.059235  ...  0.079152  0.038204 -0.098588   
...         ...       ...       ...  ...       ...       ...       ...   
63259 -0.238251  0.216923  0.253797  ...  0.245005  0.259364 -0.240164   
63260 -0.238251  0.216923  0.253797  ...  0.245005  0.259364 -0.240164   
63261 -0.238251  0.216923  0.253797  ...  0.245005  0.259364 -0.240164   
63262 -0.238251  0.216923  0.253797  ...  0.245005  0.259364 -0.240164   
63263 -0.238251  0.216923  0.253797  ...  0.245005  0.259364 -0.240164   

       Store_45  Store_46  Store_47  Store_48  Store_49  StoreType_0  \
0      0.007321  0.102424 -0.078481 -0.059800 -0.035342     0.606390   
1      0.000000  0.000000  0.000000  0.000000  0.000000     0.606390   
2      0.007321  0.102424 -0.078481 -0.059800 -0.035342     0.606390   
3      0.000000  0.000000  0.000000  0.000000  0.000000     0.606390   
4      0.007321  0.102424 -0.078481 -0.059800 -0.035342     0.606390   
...         ...       ...       ...       ...       ...          ...   
63259  0.220367  0.308087 -0.232557 -0.267985 -0.261742     0.342286   
63260  0.220367  0.308087 -0.232557 -0.267985 -0.261742     0.342286   
63261  0.220367  0.308087 -0.232557 -0.267985 -0.261742     0.342286   
63262  0.220367  0.308087 -0.232557 -0.267985 -0.261742     0.342286   
63263  0.220367  0.308087 -0.232557 -0.267985 -0.261742     0.342286   

       StoreType_1  
0        -0.532044  
1        -0.532044  
2        -0.532044  
3        -0.532044  
4        -0.532044  
...            ...  
63259    -0.444455  
63260    -0.444455  
63261    -0.444455  
63262    -0.444455  
63263    -0.444455  

[63264 rows x 55 columns]

In [3]:
import tensorflow as tf

# Number of categories and embedding dimension
n_categories = 4
embedding_dim = 3

# Define the embedding layer
embedding_layer = tf.keras.layers.Embedding(input_dim=n_categories, output_dim=embedding_dim)

# Example input indices
input_indices1 = tf.constant([0, 2, 1])
input_indices2 = tf.constant([1, 2, 0])

# Get the embedding vectors
embedding_vectors1 = embedding_layer(input_indices1)
embedding_vectors2 = embedding_layer(input_indices2)

print("Input indices:", input_indices1.numpy())
print("Embedding vectors:\n", embedding_vectors1.numpy())
print('\n')
print("Input indices:", input_indices2.numpy())
print("Embedding vectors:\n", embedding_vectors2.numpy())

Input indices: [0 2 1]
Embedding vectors:
 [[ 0.00152845 -0.02791435 -0.04230552]
 [ 0.00633038 -0.01229249 -0.00330721]
 [-0.02347742 -0.04359686 -0.02026496]]


Input indices: [1 2 0]
Embedding vectors:
 [[-0.02347742 -0.04359686 -0.02026496]
 [ 0.00633038 -0.01229249 -0.00330721]
 [ 0.00152845 -0.02791435 -0.04230552]]


In [87]:
{i:33 for i in range(10)}

{0: 33, 1: 33, 2: 33, 3: 33, 4: 33, 5: 33, 6: 33, 7: 33, 8: 33, 9: 33}